max_name_leng: 50
max_email_leng: 255
min_password_leng: 5
gravatar_size: 80
gravatar_prarams: 50
per_page: 10
password_reset_expired: 2
max_content_leng: 140
min_size_image: 5
width: 400
height: 400
picture_size: 5
